var chords = ["C", "-", "-" , "-" ,
                "-", "G7", "C" , " " ,
                "F" , " " , "G7", " ",
                "C", " ", " " , "F-C" ,
              "", "", "" , "F-C" ,
                "", "", "" , "" ,
                "" , "" , "G7", "",
                "", "", "C" , "F" ,
              "C", "F", "C" , "G7" ,
                "C ", "- ", "- " , "-",
          ]

var beatTimes = [4, 3+1, 6, 2,
                    4, 4, 6, 2,
                    6, 2, 6, 2,
                    6, 2, 2+2, 2+2,
                  3+1, 2+2, 2+2, 2+2,
                    3+1, 2+2, 2+2, 2+1+1,
                    6, 1+1, 2+2, 2+1+1,
                    6, 1+1, 2+4, 2,
                  3+1, 2+2, 4, 4,
                    4, 4, 4, 4]

var words = [
        ["Joy", "to the", "world!" , "The" ,
                  "Lord", "is", "come;" , " Let" ,
                  "earth" , "re-" , "ceive", "her",
                  "King;", "Let", "ev'" , "ry" ,
                "heart", "pre-", "pare" , "Him" ,
                  "room,", "And", "heav'n and" , "nature" ,
                  "sing,", "And", "heav'n and" , "nature",
                  "sing,", "And", "heav'n" , "and",
                "heav'n", "and", "na-" , "ture" ,
                  "sing-", "-", "." , "",
        ],
        ["Joy", "to the", "world!" , "The" ,
                  "Saviour", "re-", "igns;" , " Let" ,
                  "men" , "their" , "songs", "em-",
                  "ploy,", "While", "fields" , "and" ,
                "floods,", "Rocks,", "hills," , "and" ,
                  "plains,", "Repeat", "the" , "sounding" ,
                  "joy,", "Repeat", "the" , "sounding",
                  "joy,", "Re-", "peat" , "re-",
                "peat", "the", "soun-" , "ding" ,
                  "joy.", "-", "." , "",
        ],
        ["No", "more", "let sin," , "nor" ,
                  "sor-", "row", "grow;" , " Nor" ,
                  "thorns" , "in-" , "fest", "the",
                  "ground,", "He", "comes" , "to" ,
                "make", "His", "bles-" , "sings" ,
                  "known,", "Far", "as" , "the curse" ,
                  "is found,", "Far", "as" , "the curse",
                  "is found,", "Far", "as" , "Far",
                "as", "the", "curse" , "is" ,
                  "found.", "-", "." , "",
        ],
        ["He", "rules", "the" , "world" ,
              "with", "truth and", "grace," , " And" ,
              "makes" , "the" , "na-", "tions",
              "prove", "The", "glo-" , "ries" ,
            "of", "His", "righ-" , "teous-" ,
              "ness,", "And", "wonders" , "of his",
              "love,", "And", "wonders" , "of his",
              "love,", "And", "won-" , "ders",
            "won-", "ders", "of" , "His" ,
              "love.", "-", "." , "",
        ]
    ]

var countIn = ["1","2","3","4"]
var filename = "CCI10082018_0002.jpg"
var unitTime = 160
var numberOfVerses = 4
var swing = 0.75
